version: "3.9"

services:

  build-env:
    build:
      context: .
      dockerfile: Dockerfile
      target: msp430_toolchain

    image: msp430_toolchain

    tty: true
    command: bash

    volumes:
      - ./Workspace:/Workspace